const skills = [
    { name: "javascript", variations: ["js"] },
    { name: "node.js", variations: ["nodejs", "node js"] },
    { name: "react.js", variations: ["reactjs", "react js"] },
    { name: "react native", variations: ["react native"] },
    { name: "express.js", variations: ["expressjs", "express js"] },
    { name: "mongodb", variations: ["mongo db", "mongo"] },
    { name: "mysql", variations: ["mysql"] },
    { name: "sql", variations: [] },
    { name: "postgresql", variations: ["postgres sql"] },
    { name: "python", variations: ["python"] },
    { name: "java", variations: ["java"] },
    { name: "c++", variations: ["c++"] },
    { name: "c", variations: ["c"] },
    { name: "html", variations: ["html"] },
    { name: "css", variations: ["css"] },
    { name: "bootstrap", variations: ["bootstrap"] },
    { name: "tailwind css", variations: ["tailwind css"] },
    { name: "git", variations: ["git"] },
    { name: "github", variations: ["github"] },
    { name: "gitlab", variations: ["gitlab"] },
    { name: "bitbucket", variations: ["bitbucket"] },
    { name: "docker", variations: ["docker"] },
    { name: "kubernetes", variations: ["kubernetes"] },
    { name: "aws", variations: ["aws", "amazon web services"] },
    { name: "azure", variations: ["azure"] },
    { name: "gcp", variations: ["gcp"] },
    { name: "firebase", variations: ["firebase"] },
    { name: "redux", variations: ["redux"] },
    { name: "mobx", variations: ["mobx"] },
    { name: "vue.js", variations: ["vuejs", "vue js"] },
    { name: "angular", variations: ["angular"] },
    { name: "typescript", variations: ["typescript"] },
    { name: "oauth", variations: ["oauth"] },
    { name: "soap api", variations: ["soap api"] },
    { name: "graphql", variations: ["graphql"] },
    { name: "rest api", variations: ["rest api"] },
    { name: "rest", variations: ["rest"] },
]

module.exports = skills;